function(add_executable_with_libraries target_name source_file)
    add_executable(${target_name} ${source_file})
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
        if (MSVC)
            target_link_directories(${target_name} PRIVATE ${CMAKE_SOURCE_DIR}/lib/libusb/VS2022/MS64/static)
            target_link_libraries(${target_name} PRIVATE efex libusb-1.0.lib)
        else ()
            target_link_directories(${target_name} PRIVATE ${CMAKE_SOURCE_DIR}/lib/libusb/MinGW64/static)
            target_link_libraries(${target_name} PRIVATE efex libusb-1.0.a)
        endif ()
    else()
        target_link_libraries(${target_name} PRIVATE efex usb-1.0)
    endif ()
endfunction()

